### ISSUE TITLE
Crash onLicenseCheck

### ISSUE THREAD

**Issue by myrmidon-media** [Viblast/android-pdn-sdk#4]
``` log
E/AndroidRuntime: FATAL EXCEPTION: Thread-4190
Process: com.mobdro.android, PID: 12860
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6556)
    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:907)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.View.requestLayout(View.java:18728)
    at android.view.ViewGroup.addView(ViewGroup.java:4143)
    at android.view.ViewGroup.addView(ViewGroup.java:4086)
    at android.view.ViewGroup.addView(ViewGroup.java:4059)
    at com.viblast.android.ViblastView.showWatermark(ViblastView.java:138)
    at com.viblast.android.ViblastPlayer.onLicenseChecked(ViblastPlayer.java:213)
    at com.viblast.android.ViblastLib.onLicenseChecked(ViblastLib.java:20)

```

**Comment by ptanov** [comment]
This is a very strange bug. Actually I can't reproduce this issue (tested on several devices).
`onLicenseChecked()` callback is called on the main (UI) thread from JNI. To confirm that, I'm now explicitly pushing it on the main thread.
I'd appreciate it if you could acknowledge whether or not it works for you now.

Thank you for the bug report.
